"""create_core_tables

Revision ID: 39385cbbf494
Revises: 00d31068b201
Create Date: 2026-04-28 09:19:01.688016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39385cbbf494'
down_revision: Union[str, None] = '00d31068b201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='faculty', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('faculty', 'cataloger', 'librarian')", name=op.f('ck_users_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(course_code, '') || ' ' || coalesce(course_title, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_courses_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=False)
    op.create_index('ix_courses_search_vector', 'courses', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('syllabi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.CheckConstraint("file_type IN ('pdf', 'docx')", name=op.f('ck_syllabi_syllabi_file_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'processed', 'confirmed')", name=op.f('ck_syllabi_syllabi_status_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_syllabi_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_syllabi_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_syllabi'))
    )
    op.create_index(op.f('ix_syllabi_course_id'), 'syllabi', ['course_id'], unique=False)
    op.create_index(op.f('ix_syllabi_uploaded_by'), 'syllabi', ['uploaded_by'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('syllabus_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('topic_text', sa.Text(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('llm_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("source IN ('extracted', 'manual')", name=op.f('ck_topics_topics_source_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_topics_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabi.id'], name=op.f('fk_topics_syllabus_id_syllabi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index(op.f('ix_topics_course_id'), 'topics', ['course_id'], unique=False)
    op.create_index(op.f('ix_topics_syllabus_id'), 'topics', ['syllabus_id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('keyword_text', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_keywords_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords'))
    )
    op.create_index(op.f('ix_keywords_topic_id'), 'keywords', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keywords_topic_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_topics_syllabus_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_course_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_syllabi_uploaded_by'), table_name='syllabi')
    op.drop_index(op.f('ix_syllabi_course_id'), table_name='syllabi')
    op.drop_table('syllabi')
    op.drop_index('ix_courses_search_vector', table_name='courses', postgresql_using='gin')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
